name: Playwright Regression Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain to test'
        required: false
        default: 'https://www.google.com'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium

    - name: Run Playwright tests
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.domain }}" ]; then
          python test_site.py --domain "${{ github.event.inputs.domain }}"
        else
          python test_site.py
        fi

    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots
        path: screenshots/
        retention-days: 30

    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: logs
        path: logs/
        retention-days: 30
